### ISSUE TITLE
Error on Android 6 (API 22) - can't process PN payload on javascript

### ISSUE THREAD

**Issue by otmezger** [thefuturehaus/parse-push-plugin#4]
Hi, 

I found a problem with this plugin using Android 6 (compiled with API 22). I found 2 ways of using this plugin:

*_A) Initialise on Java *_

When I initialise the parse plugin from MainApplication.java I do receive the push notification sent from Parse, but I can’t process it’s payload from javascript. 

The code for registering in Javascript returns with a `alert. error registering device: java.lang.IllegalStateException:ParsePlugins is already initialised`... Why can't I register the plugin with parse with JavaScript?

**B) Initialise ONLY on JavaScript**

On the other hand, if I initialise the parse plugin from javascript alone with the register function, I do get push notifications and can process it's payload as long as the app is running. If the app is in background or closed, the app crashed even before the notification arrives. 

This is the crash error :

`java.lang.RuntimeException: Unable to create service com.parse.PushService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.parse.ParsePlugins$Android.applicationContext()' on a null object reference`

Any idea on how to solve this? 

Thanks

**Comment by kmorey** [comment]
Can confirm it's a problem for me as well. I remember having this problem before, but I'm not sure what the fix was. I'll dig in and let you know.

**Comment by kmorey** [comment]
Try modifying ParsePlugin.registerDevice to ignore the exception from it being already initialized.

```
            try {
                Parse.initialize(new Parse.Configuration.Builder(cordova.getActivity())
                    .applicationId(appId)
                    .clientKey(null)
                    .server(server)
                    .build()
                );
            } catch (IllegalStateException e) { }
```

**Comment by otmezger** [comment]
@kmorey your code was part of the solution. We implemented a missing part in the plugin as well (PN payload in Javascript when the app was closed). We still need to implement it on iOS... See #6.
