### ISSUE TITLE
GCMSenderId not sent to server

### ISSUE THREAD

**Issue by mymanga** [thefuturehaus/parse-push-plugin#7]
The plugin installs fine and forwards installation data to the Parse Server (self hosted) but it doesnt come with the GCMSenderId for android. I even tried installing it with the official phonegap push plugin just to see if it works.. no diffrence

**Comment by otmezger** [comment]
We'll try to check on that. thanks

**Comment by otmezger** [comment]
I this what you mean? 
https://parse.com/docs/android/guide#push-notifications

See Setting up push. I think the senderID is set up in the parse.com dashboard. If you are using your own parse-server, look for the documentation there.

**Comment by otmezger** [comment]
@kmorey I think you can close this now.
